### ISSUE TITLE
Cast error on GetAzureSubscriptionUtilization.java. Latest version

### ISSUE THREAD

**Issue by renutz** [microsoft/Partner-Center-Java-Samples#10]
# Steps to reproduce

Running https://github.com/microsoft/Partner-Center-Java-Samples/blob/master/sdk/src/main/java/com/microsoft/store/partnercenter/samples/utilization/GetAzureSubscriptionUtilization.java

## Actual behavior

ClassCastException occured : okhttp3.Response cannot be cast to com.microsoft.store.partnercenter.models.ResourceCollection

Running partnercenter-1.12.0.

**Comment by isaiahwilliams** [comment]
@renutz would it be possible for you to share a Fiddler trace for this? It will help me debug this issue a little more quickly.

Isaiah Williams
________________________________

**Comment by renutz** [comment]
Hi Isaiah. Thanks for the promptness.

There is no change at all from the samples. Compiling and having an CSP Appid, appkey should be enough to find the error.

**Comment by isaiahwilliams** [comment]
@renutz with my test environment the request is executing as expected. It would be helpful to see a trace of the request that is failing. Specifically I curious if the request for Azure Utilization records is returning a response with a HTTP status code of 204. If you could let me know the status code of your response it should help narrow down what is happening.

**Comment by renutz** [comment]
Understood. I'll see what I can do from here. Thanks

**Comment by renutz** [comment]
We just realized we were using an old version client-runtime (1.6.2 instead of 1.6.5). After the upgrade it worked.

Sorry to bother you and thanks for the attention!

**Comment by thebitmuncher** [comment]
This azure internal class cast exception is still happening with the version:
```
		<dependency>
		    <groupId>com.microsoft.azure</groupId>
		    <artifactId>azure</artifactId>
		    <version>1.35.1</version>
		</dependency>
```
`java.lang.ClassCastException: class okhttp3.Response cannot be cast to class com.microsoft.store.partnercenter.models.ResourceCollection `

I've observed the exception when calling the query() method with these conditions:
```
	new DateTime().minusDays(2),  //startTime
	new DateTime(), 			  // endTime  (notice empty constructor(current date time))
	AzureUtilizationGranularity.HOURLY
```
I also observed the exception with these conditions:
```
	new DateTime().minusHours(2),  //startTime
	new DateTime().minusHours(1),  // endTime  
	AzureUtilizationGranularity.HOURLY
```

When I use these slightly different options, the exception does not happen and I receive query results:
```
	new DateTime().minusDays(2),  //startTime
	new DateTime().minusDays(1),  // endTime  (notice 1 day in the past instead of current DateTime)
	AzureUtilizationGranularity.HOURLY, 
```

It looks like the issue is that the query method is either:
- unable to handle the "current date time" as the endTime param with at least the HOURLY granularity
or
- unable to handle returning an empty collection when no results are found for these conditions

Can the issue be reopened?
